#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
# Code Solved by Simon Biswas
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    left=0
    right=0
    p1=len(arr)-1
    for i in range(0,len(arr)):
        s=arr[i][i]
        left=left+s
    for j in range(0,len(arr)):
        p=arr[j][p1]
        right=right+p
        p1=p1-1
    s1=abs(left-right)
    return s1
        
        
    # Write your code here
      
    
    
    
        
        
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
