#!/bin/python3

import os
import sys

#
# Complete the simpleArraySum function below.
# Code Solved by Simon Biswas
#
def simpleArraySum(ar):
    s=0
    for i in range(0,len(ar)):
        p=int(ar[i])
        s=s+p
    return s
        
    #
    # Write your code here.
    #

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = simpleArraySum(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
