#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the catAndMouse function below.
# Code Solved by Simon Biswas
def catAndMouse(x, y, z):
    x1=abs(z-x)
    y1=abs(z-y)
    if x1==y1: 
        return 'Mouse C'
    if x1>y1:
         return 'Cat B'
    if y1>x1: 
        return 'Cat A'

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        xyz = input().split()

        x = int(xyz[0])

        y = int(xyz[1])

        z = int(xyz[2])

        result = catAndMouse(x, y, z)

        fptr.write(result + '\n')

    fptr.close()
