#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the viralAdvertising function below.
# Code Solved by Simon Biswas
def viralAdvertising(n):
    share=0
    Liked=0
    cumulative=0
    for m in range(1,n+1):
        if m==1:
            share=5
            Liked=5//2
            cumulative=Liked
        if m>1:
            share=Liked*3
            Liked=share//2
            cumulative=cumulative+Liked
    return cumulative
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
