#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
# Code Solved by Simon Biswas
def sockMerchant(n, ar):
    p=list()
    p2=list()# saving unique socks
    count=0
    for i in ar:
        if i not in p2:
            p2.append(i)
            p1=ar.count(i)
            p.append(p1)
    for i in p:
        j=i//2
        count=count+j
    return count
    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
