#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the aVeryBigSum function below.
# Code Solved by Simon Biswas
def aVeryBigSum(ar):
    s=0
    for i in range(0,len(ar)):
        p=ar[i]
        s=s+p
    return s
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = aVeryBigSum(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
