#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the saveThePrisoner function below.
# Code Solved by Simon Biswas
def saveThePrisoner(n, m, s):
    p=s+m-1
    p1=p%n
    if p1==0: return n
    else: return p1
    

        
    #m=m-1
    #i=i+1

    
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        nms = input().split()

        n = int(nms[0])

        m = int(nms[1])

        s = int(nms[2])

        result = saveThePrisoner(n, m, s)

        fptr.write(str(result) + '\n')

    fptr.close()
