#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
# Code Solved by Simon Biswas
def countApplesAndOranges(s, t, a, b, apples, oranges):
    apple=0
    orange=0
    for i in range(0,len(apples)):
        apples[i]=apples[i]+a
    for i in range(0,len(apples)):
        if apples[i]>=s and apples[i]<=t:
            apple=apple+1
            
    for j in range(0,len(oranges)):
        oranges[j]=oranges[j]+b
    for j in range(0,len(oranges)):
        if oranges[j]>=s and oranges[j]<=t:
            orange=orange+1
            
    print(apple)
    print(orange)
                
    
    

if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
