#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the utopianTree function below.
# Code Solved by Simon Biswas
def utopianTree(n):
    count=0
    for i in range(0,n+1):
        if i%2==0 : count=count+1
        if i%2!=0 : count=count*2
    return count
  
                
    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        result = utopianTree(n)

        fptr.write(str(result) + '\n')

    fptr.close()
