#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
# Code Solved by Simon Biswas
def plusMinus(arr):
    pos=0
    neg=0
    zero=0
    l=len(arr)
    for i in range(0,len(arr)):
        p=arr[i]
        if p>0 : pos=pos+1
        if p<0 : neg=neg+1
        if p==0 : zero=zero+1
    print("{0:6f}".format(pos/l))
    print("{0:6f}".format(neg/l))
    print("{0:6f}".format(zero/l))

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
